### ISSUE TITLE
Define in config which room pushes the message

### ISSUE THREAD

**Issue by floviolleau** [madmax28/navi#3]
Hi,

I would like to push to a specific room where I can define the corresponding id in the config file.

Would it be possible?

Thanks a lot!

**Comment by madmax28** [comment]
Hi @floviolleau,

I have added support for this in b11c564ffe233a81da5bd27e75702b407fe6bc36.
You can now specify room ids in the config using the raw room id format (starting with !). If the room is private, make sure you invite Navi to it.

Hope that works for you!

**Comment by floviolleau** [comment]
Hi @madmax28 

Thanks a lot!

But I have a small issue.

I have cloned twice your project on the same machine.

# Currently

I changed the reading location of the config file to have two independent installations with different config.
Folder A, with config A and default room (room A) (only user id in notifications section, no rooms) 
```diff
-- a/navi/cli.py
+++ b/navi/cli.py
@@ -20,7 +20,7 @@ Its default configuration file is ~/.navi.cfg. Other files can be used with the
 
     @staticmethod
     def _default_config_file():
-        return os.path.expanduser("~/.navi.cfg")
+        return os.path.expanduser("/home/user/projects/riot-push-folder-A/config.cfg")
 
     def _parse_cli_args(self):
         parser = ArgumentParser(description=self._desc,
```

Folder B, with config B and room B (no user id in notifications section, in rooms, a room B id). navi/cli.py point to config B

# What happens:
When calling navi from folder A, message is pushed to room A
When calling navi from folder B, message is pushed to room B **but bot is removed on room A** and I cannot push to room A anymore (I must manually invite it)

If I specify a user in config B and a room, bot remains in room A but message is sent both to room A and B

# What is expected:
When calling navi from folder A, message is pushed to room A (with config: user id specified and rooms leaved as default)
When calling navi from folder B, message is pushed to room B (with config: user id specified?/not specified? and rooms specified)
Bot must remains in both rooms

Thanks!

**Comment by madmax28** [comment]
Hi @floviolleau,

I'm not quite sure how to implement this. I could let Navi skip the cleanup step, but in case of  **config A**, it will push to every room that you are in, even the one from **config B**. How would Navi know which room it should push to in that case?

As a simple workaround, I suggest you create two separate bot accounts, each with their own config file. Would that work for you?

By the way, you don't need to clone the repository twice. You can select which config file to use from the command line:
``` bash
navi -c /path/to/navi.cfg -m "Hello!"
```

**Comment by floviolleau** [comment]
Hi,

What I suggest is when a room is specified, it push only to that room. If several rooms are specified, it push to all rooms specified. When room is not specified, it fallback to the default room where the bot is in.

Thanks for the suggestions, I will give a try it can be okey for me to have different bots. I'm the owner of my server :).

**Comment by floviolleau** [comment]
Hi,

What is mentionned [here](https://github.com/madmax28/navi/issues/3#issuecomment-1290981449) works fine

Thanks
